# pyproject.toml
[project]
name = "mypkg"
version = "0.1.0"
description = "A minimal Python package example"
authors = [{ name = "Your Name", email = "your.email@example.com" }]
license = { file = "LICENSE" }
dependencies = ["requests"]  # Example dependency

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools.package-data]
"mypkg" = ["data/*.json"]
[build-system]
requires = ["setuptools", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"
