site_name: My MkDocs Project
theme:
  name: material

plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - Markdown Guide: markdown-guide.md
  - Diagrams: diagrams.md
  - Navigation Tips: navigation.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
