site_name: GitHub Docs Site
nav:
  - Home: README.md
  - Getting Started: docs/getting-started.md

theme:
  name: material

markdown_extensions:
  - toc
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.details
